const $=id=>document.getElementById(id);
const bookId=location.pathname.split('/')[2];let book,active=0,voice,audio;
function sourceUrl(page){return `/book/${bookId}/source.pdf#page=${page}`;}
function stop(){if('speechSynthesis' in window)speechSynthesis.cancel();if(audio){audio.pause();audio.currentTime=0;audio=null;}}
function render(index){stop();active=index;const chapter=book.chapters[index];$('chapterTitle').textContent=chapter.title;$('progress').max=book.chapters.length;$('progress').value=index+1;$('caption').textContent=chapter.caption;$('passage').textContent=chapter.passage.text;$('sourceLink').href=sourceUrl(chapter.passage.page);const original=$('originalSourceLink');original.hidden=!chapter.source_url;if(chapter.source_url)original.href=chapter.source_url;else original.removeAttribute('href');$('question').textContent=chapter.quiz.question;$('answers').replaceChildren();$('feedback').textContent='';chapter.quiz.options.forEach((option,i)=>{const b=document.createElement('button');b.textContent=option;b.onclick=()=>{if(i===chapter.quiz.answer){$('feedback').textContent='Correct. This answer comes from page '+chapter.passage.page+'.';}else{$('feedback').replaceChildren(document.createTextNode('Look again at the source: '));const a=document.createElement('a');a.href=sourceUrl(chapter.passage.page);a.target='_blank';a.rel='noopener';a.textContent='jump to page '+chapter.passage.page; $('feedback').append(a);}};$('answers').append(b)});document.querySelectorAll('#chapters button').forEach((b,i)=>b.setAttribute('aria-current',i===index));}
fetch(`/book/${bookId}/data.json`).then(r=>{if(!r.ok)throw Error('Book unavailable');return r.json()}).then(data=>{book=data;$('title').textContent=data.title;$('scope').textContent=data.scope;data.chapters.forEach((ch,i)=>{const b=document.createElement('button');b.textContent=ch.title;b.onclick=()=>render(i);$('chapters').append(b)});$('voiceNote').textContent=data.narration_mode==='edge-tts'?'Narration synthesized with edge-tts.':'Narration uses your device’s voice.';render(0)}).catch(e=>{$('title').textContent=e.message});
$('play').onclick=()=>{if(!book)return;stop();const chapter=book.chapters[active];if(chapter.audio){audio=new Audio(`/book/${bookId}/${chapter.audio}`);audio.volume=Number($('volume').value);audio.playbackRate=Number($('speed').value);audio.play();return;}if(!('speechSynthesis' in window)){$('voiceNote').textContent='Narration is unavailable in this browser.';return;}voice=new SpeechSynthesisUtterance(chapter.narration);voice.volume=Number($('volume').value);voice.rate=Number($('speed').value);speechSynthesis.speak(voice)};$('stop').onclick=stop;$('volume').oninput=()=>{if(voice)voice.volume=Number($('volume').value);if(audio)audio.volume=Number($('volume').value)};
$('speed').onchange=()=>{if(audio)audio.playbackRate=Number($('speed').value);if(voice&&speechSynthesis.speaking){speechSynthesis.cancel();$('play').click()}};
$('guideForm').onsubmit=async event=>{event.preventDefault();const result=$('guideResult');result.textContent='Searching this book…';try{const response=await fetch(`/book/${bookId}/ask`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:$('guideQuestion').value})});if(!response.ok)throw Error('Guide unavailable');const answer=await response.json();result.replaceChildren(document.createTextNode(answer.message));if(answer.found){const button=document.createElement('button');button.type='button';button.textContent=`Check ${answer.chapter_title} (source page ${answer.page})`;button.onclick=()=>{render(answer.chapter_index);$('chapterTitle').scrollIntoView()};result.append(document.createElement('br'),button);}}catch{result.textContent='Guide unavailable. You can still browse the chapters above.'}};
