#!/usr/bin/env node
import fs from 'node:fs/promises';
import path from 'node:path';
import crypto from 'node:crypto';
import os from 'node:os';
import { execFile } from 'node:child_process';
import { promisify } from 'node:util';
import { lookup } from 'node:dns/promises';
import { isIP } from 'node:net';
import https from 'node:https';
const run=promisify(execFile);
const root=process.env.GLOWHUM_DROPS_DIR||'/data/glowhum-drops';
const baseUrl=process.env.PUBLIC_BASE_URL;
function publicIp(ip){if(isIP(ip)===4){const [a,b]=ip.split('.').map(Number);return !(a===0||a===10||a===127||a>=224||(a===100&&b>=64&&b<=127)||(a===169&&b===254)||(a===172&&b>=16&&b<=31)||(a===192&&b===168));}if(isIP(ip)===6)return !(/^(::|fc|fd|fe[89ab]|::ffff:)/i.test(ip));return false;}
async function fetchPdf(url){const parsed=new URL(url);if(parsed.protocol!=='https:'||parsed.username||parsed.password||parsed.port)throw Error('Only public HTTPS PDF URLs are allowed');const addresses=await lookup(parsed.hostname,{all:true});if(!addresses.length||addresses.some(a=>!publicIp(a.address)))throw Error('PDF host is not public');const pinned=addresses[0].address;return new Promise((resolve,reject)=>{const request=https.get(parsed,{lookup:(_host,_options,cb)=>cb(null,pinned,isIP(pinned)),timeout:30000},res=>{if(res.statusCode!==200){res.resume();reject(Error(`PDF download failed: ${res.statusCode}`));return;}const chunks=[];let size=0;res.on('data',chunk=>{size+=chunk.length;if(size>12*1024*1024){request.destroy(Error('PDF is too large'));return;}chunks.push(chunk)});res.on('end',()=>{const bytes=Buffer.concat(chunks);if(bytes.length<100||bytes.subarray(0,5).toString()!=='%PDF-')reject(Error('Invalid PDF'));else resolve(bytes)});res.on('error',reject)});request.on('timeout',()=>request.destroy(Error('PDF download timed out')));request.on('error',reject)});}

function clean(text){return text.replace(/\s+/g,' ').trim();}
function pronunciation(text){return text.replace(/\b([A-Za-z]+)\s*\/\s*([A-Za-z]+)\b/g,'$1 or $2').replace(/%/g,' percent').replace(/≥/g,' greater than or equal to ').replace(/≤/g,' less than or equal to ').replace(/α/g,' alpha ').replace(/β/g,' beta ').replace(/μg/g,' micrograms').replace(/\bmg\b/g,'milligrams').replace(/\bmmHg\b/g,'millimeters of mercury');}
function passages(pages){return pages.map((text,i)=>({page:i+1,text:clean(text)})).filter(p=>p.text.length>=80).map(p=>({...p,text:p.text.slice(0,460)}));}
export async function buildBook(pdf, title){const tmp=await fs.mkdtemp(path.join(os.tmpdir(),'glowhum-book-'));try{const input=path.join(tmp,'source.pdf');await fs.writeFile(input,pdf);const {stdout}=await run('pdftotext',['-enc','UTF-8','-layout',input,'-'],{maxBuffer:20*1024*1024});const pages=stdout.split('\f').filter(x=>x.trim());const sources=passages(pages);if(sources.length<2)throw Error('PDF has too little extractable text');const picked=sources.filter((_,i)=>i%Math.max(1,Math.ceil(sources.length/8))===0).slice(0,8);const chapters=picked.map((p,i)=>{const alternatives=sources.filter(x=>x.page!==p.page&&x.text!==p.text).slice((i+1)%Math.max(1,sources.length-1)).concat(sources).filter(x=>x.page!==p.page).slice(0,2);const correct=(i%3);const options=alternatives.map(x=>x.text.slice(0,125));const optionSources=alternatives.map(x=>({page:x.page,text:x.text}));options.splice(correct,0,p.text.slice(0,125));optionSources.splice(correct,0,{page:p.page,text:p.text});return {title:`Chapter ${i+1} · Page ${p.page}`,caption:p.text,passage:p,narration:pronunciation(p.text),scene:{type:'progress',source_page:p.page},quiz:{question:`Which statement appears on source page ${p.page}?`,options,option_sources:optionSources,answer:correct,source_page:p.page,source_text:p.text}}});if(chapters.some(ch=>ch.quiz.options.length!==3||ch.quiz.options[ch.quiz.answer]!==ch.passage.text.slice(0,125)||ch.quiz.option_sources.some((source,i)=>source.text.slice(0,125)!==ch.quiz.options[i])))throw Error('Quiz provenance check failed');const medical=/\b(patient|clinical|diagnos\w*|treatment|disease|medicine|surgery|mortality|hypertension|diabetes|therapy|symptom\w*|prognosis|dosage|pharmacology)\b/i.test(title+' '+stdout);return {title,scope:`${pages.length} source pages · ${chapters.length} chapters · ${medical?'Clinical review required':'Source-linked learning'}`,source_pages:pages.length,medical,chapters,source_sha256:crypto.createHash('sha256').update(pdf).digest('hex')};}finally{await fs.rm(tmp,{recursive:true,force:true});}}
export async function publish(orderId){if(!/^cs_[A-Za-z0-9_]+$/.test(orderId))throw Error('Invalid order ID');if(!baseUrl||!new URL(baseUrl).protocol.startsWith('https'))throw Error('PUBLIC_BASE_URL must be HTTPS');const dir=path.join(root,'drops',orderId);const receipt=JSON.parse(await fs.readFile(path.join(dir,'receipt.json'),'utf8'));if(receipt.product!=='glowhum_web_book_v1'||receipt.status!=='paid')throw Error('No paid Web Book order');const statePath=path.join(dir,'webbook-state.json');try{const current=JSON.parse(await fs.readFile(statePath,'utf8'));if(current.status==='published')return current;}catch(e){if(e.code!=='ENOENT')throw e;}
await fs.writeFile(statePath,JSON.stringify({status:'rendering',started_at:new Date().toISOString()}));const started=Date.now();try{const pdf=await fetchPdf(receipt.report_url);const book=await buildBook(pdf,receipt.topic||'Your Web Book');if(book.medical){let approval;try{approval=JSON.parse(await fs.readFile(path.join(dir,'clinical-approval.json'),'utf8'));}catch{throw Error('Clinical review required: missing clinical-approval.json');}if(approval.order_id!==orderId||approval.source_sha256!==book.source_sha256||!approval.reviewer||Number.isNaN(Date.parse(approval.approved_at)))throw Error('Clinical review approval does not match this order and PDF');}const bookId=crypto.randomBytes(16).toString('hex');const bookDir=path.join(root,'books',bookId);await fs.mkdir(bookDir,{recursive:true});await fs.writeFile(path.join(bookDir,'source.pdf'),pdf);if(process.env.WEB_BOOK_EDGE_TTS_BIN){for(let i=0;i<book.chapters.length;i++){const file=`audio-${i}.mp3`;await run(process.env.WEB_BOOK_EDGE_TTS_BIN,['--voice','en-US-AriaNeural','--text',book.chapters[i].narration,'--write-media',path.join(bookDir,file)],{timeout:120000});book.chapters[i].audio=file;}book.narration_mode='edge-tts';}else{book.narration_mode='browser speech';}await fs.writeFile(path.join(bookDir,'data.json'),JSON.stringify(book));const state={status:'published',book_id:bookId,base_url:new URL(baseUrl).origin,published_at:new Date().toISOString(),elapsed_seconds:Math.round((Date.now()-started)/1000),source_sha256:book.source_sha256,source_pages:book.source_pages,chapters:book.chapters.length,model_spend_usd:0,model_spend_basis:book.narration_mode==='edge-tts'?'No metered model provider called; Edge TTS service used':'No model provider called; deterministic source extraction'};await fs.writeFile(statePath,JSON.stringify(state,null,2));return state;}catch(e){await fs.writeFile(statePath,JSON.stringify({status:'failed',error:e.message,failed_at:new Date().toISOString()}));throw e;}}
if(process.argv[1]&&import.meta.url===new URL(`file://${path.resolve(process.argv[1])}`).href){const id=process.argv[2];if(!id){console.error('Usage: node scripts/run-webbook.mjs <paid-order-id>');process.exit(2);}publish(id).then(x=>console.log(JSON.stringify(x))).catch(e=>{console.error(e.message);process.exitCode=1});}
